# Generated by Django 4.1.3 on 2024-05-06 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolMaster', '0002_school_school_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('Isdeleted', models.BooleanField(blank=True, default=False, null=True)),
                ('school_code', models.CharField(blank=True, max_length=255, null=True)),
                ('SchoolId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolMaster.school')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
    ]
