# Generated by Django 4.1.3 on 2024-05-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolMaster', '0003_academicyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_logo',
            field=models.ImageField(blank=True, null=True, upload_to='Schoollogos/', verbose_name='school logo'),
        ),
    ]
