# Generated by Django 4.1.3 on 2024-05-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolMaster', '0004_school_school_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-startdate']},
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['startdate', 'enddate'], name='SchoolMaste_startda_aeee6e_idx'),
        ),
    ]
