# Generated by Django 4.1.3 on 2024-05-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassMaster', '0001_initial'),
        ('SchoolMaster', '0005_alter_academicyear_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('announcement_text', models.TextField(default=True, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('school_code', models.CharField(blank=True, max_length=50, null=True)),
                ('classes_id', models.ManyToManyField(to='ClassMaster.class')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
    ]
