# Generated by Django 4.1.3 on 2024-05-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolMaster', '0006_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='classes_id',
        ),
    ]
