# Generated by Django 4.1.3 on 2024-05-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolMaster', '0007_remove_announcement_classes_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
