# Generated by Django 4.1.3 on 2024-04-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherMaster', '0002_alter_teachersubject_teacherid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersubject',
            name='TeacherId',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
