# Generated by Django 4.1.3 on 2024-04-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherMaster', '0003_alter_teachersubject_teacherid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersubject',
            name='TeacherId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
