# Generated by Django 5.0.6 on 2024-06-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceMaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattendance',
            name='IsPresent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
