# Generated by Django 4.1.3 on 2024-04-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_school_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='PasswordSet',
            field=models.BooleanField(default=False),
        ),
    ]
