# Generated by Django 4.1.3 on 2024-04-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_address_user_passwordset_user_school_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Address',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
