# Generated by Django 4.1.3 on 2024-04-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_passwordset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
