# Generated by Django 4.1.3 on 2024-04-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_code',
            field=models.CharField(blank=True, max_length=101, null=True),
        ),
    ]
