# Generated by Django 4.1.3 on 2024-04-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTableMaster', '0002_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='Month',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='Week',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='Year',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
