# Generated by Django 4.1.3 on 2024-04-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTableMaster', '0003_timetable_month_timetable_week_timetable_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='Month',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='Week',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='Year',
        ),
        migrations.AddField(
            model_name='timetable',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Day',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
