# Generated by Django 4.1.3 on 2024-05-21 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SchoolMaster', '0004_school_school_logo'),
        ('ClassMaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesDistributionsBreakdowns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('name', models.CharField(blank=True, max_length=1150, null=True)),
                ('amount', models.CharField(blank=True, max_length=150, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('fees_distributions_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolMaster.academicyear')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeesDistributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=150, null=True)),
                ('breakdown', models.BooleanField(default=False)),
                ('academic_year_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolMaster.academicyear')),
                ('clas_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ClassMaster.class')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
    ]
