# Generated by Django 4.1.3 on 2024-05-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeesMaster', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feesdistributions',
            old_name='clas_id',
            new_name='class_id',
        ),
    ]
