# Generated by Django 4.1.3 on 2024-05-23 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FeesMaster', '0002_rename_clas_id_feesdistributions_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesdistributionsbreakdowns',
            name='fees_distributions_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FeesMaster.feesdistributions'),
        ),
    ]
