# Generated by Django 4.1.3 on 2024-05-24 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClassMaster', '0001_initial'),
        ('Parent_StudentMaster', '0002_studentclasslog_rollno'),
        ('FeesMaster', '0003_alter_feesdistributionsbreakdowns_fees_distributions_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeesLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('amount', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, default='UnPaid', max_length=150, null=True)),
                ('Date', models.DateField(null=True)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ClassMaster.class')),
                ('fees_distributions_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FeesMaster.feesdistributions')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Parent_StudentMaster.students')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
    ]
