# Generated by Django 5.0.6 on 2024-05-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeesMaster', '0004_studentfeeslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeeslog',
            name='payment_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
