# Generated by Django 5.0.6 on 2024-05-28 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeesMaster', '0005_studentfeeslog_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfeeslog',
            name='status',
        ),
        migrations.AddField(
            model_name='studentfeeslog',
            name='termid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FeesMaster.feesdistributionsbreakdowns'),
        ),
        migrations.AlterField(
            model_name='studentfeeslog',
            name='payment_type',
            field=models.CharField(blank=True, default='Partial', max_length=150, null=True),
        ),
    ]
