# Generated by Django 5.0.6 on 2024-05-29 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeesMaster', '0006_remove_studentfeeslog_status_studentfeeslog_termid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeeslog',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='studentfeeslog',
            name='payment_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
