# Generated by Django 5.0.6 on 2024-05-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeesMaster', '0008_remove_studentfeeslog_payment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfeeslog',
            name='amount',
        ),
    ]
