# Generated by Django 5.0.6 on 2024-07-09 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0005_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=550, null=True)),
                ('school_code', models.CharField(blank=True, max_length=550, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('to_student', models.BooleanField(blank=True, default=False, null=True)),
                ('student_id', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('notification_title', models.CharField(max_length=51)),
                ('notification_message', models.CharField(max_length=500, null=True)),
                ('notification_read', models.BooleanField(default=False)),
                ('school_code', models.CharField(blank=True, max_length=550, null=True)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NotificationMaster.notificationtypemaster')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
    ]
