# Generated by Django 5.0.6 on 2024-07-10 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotificationMaster', '0002_remove_notificationtypemaster_school_code'),
        ('User', '0005_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmaster',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='notificationmaster',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='User.user'),
        ),
    ]
