# Generated by Django 5.0.6 on 2024-07-10 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotificationMaster', '0003_notificationmaster_from_user_and_more'),
        ('Parent_StudentMaster', '0008_remove_studentclasslog_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmaster',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='notificationmaster',
            name='to_student',
        ),
        migrations.AddField(
            model_name='notificationmaster',
            name='from_user_studentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user_studentid', to='Parent_StudentMaster.students'),
        ),
        migrations.AddField(
            model_name='notificationmaster',
            name='to_user_studentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user_studentid', to='Parent_StudentMaster.students'),
        ),
    ]
