# Generated by Django 5.0.6 on 2024-06-10 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClassMaster', '0002_classteacher'),
        ('SchoolMaster', '0008_delete_announcement'),
        ('SubjectMaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=550, null=True)),
                ('school_code', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('TypeName', models.CharField(blank=True, max_length=150, null=True)),
                ('school_code', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarkSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('AcademicYearId', models.BigIntegerField(blank=True, null=True)),
                ('ClassId', models.BigIntegerField(blank=True, null=True)),
                ('StudentId', models.BigIntegerField(blank=True, null=True)),
                ('subID', models.CharField(blank=True, max_length=255, null=True)),
                ('ObtainedMarks', models.CharField(blank=True, max_length=255, null=True)),
                ('OutOfMarks', models.FloatField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=150, null=True)),
                ('Exam', models.BigIntegerField(blank=True, null=True)),
                ('RollNo', models.CharField(blank=True, max_length=150, null=True)),
                ('school_code', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Examstarttime', models.CharField(blank=True, max_length=255, null=True)),
                ('Examendtime', models.CharField(blank=True, max_length=255, null=True)),
                ('InvigilatorId', models.CharField(blank=True, max_length=250, null=True)),
                ('totalMarks', models.CharField(blank=True, max_length=255, null=True)),
                ('passingmarks', models.CharField(blank=True, max_length=255, null=True)),
                ('reportTime', models.CharField(blank=True, max_length=255, null=True)),
                ('RoomNo', models.CharField(blank=True, max_length=255, null=True)),
                ('Instructions', models.TextField(blank=True, null=True)),
                ('school_code', models.CharField(blank=True, max_length=150, null=True)),
                ('AcademicYearId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolMaster.academicyear')),
                ('ClassId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ClassMaster.class')),
                ('SubjectId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SubjectMaster.subject')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MarksheetMaster.exam')),
                ('ExamType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MarksheetMaster.examtype')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamTypeMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('Marks', models.CharField(blank=True, max_length=150, null=True)),
                ('passingmarks', models.CharField(blank=True, max_length=150, null=True)),
                ('school_code', models.CharField(blank=True, max_length=150, null=True)),
                ('Typeid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MarksheetMaster.examtype')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
    ]
