# Generated by Django 4.1.3 on 2024-05-03 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectMaster', '0001_initial'),
        ('ClassMaster', '0001_initial'),
        ('MarksheetMaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Examstarttime', models.CharField(blank=True, max_length=255, null=True)),
                ('Examendtime', models.CharField(blank=True, max_length=255, null=True)),
                ('InvigilatorId', models.CharField(blank=True, max_length=250, null=True)),
                ('totalMarks', models.CharField(blank=True, max_length=255, null=True)),
                ('reportTime', models.CharField(blank=True, max_length=255, null=True)),
                ('RoomNo', models.CharField(blank=True, max_length=255, null=True)),
                ('Instructions', models.TextField(blank=True, null=True)),
                ('school_code', models.CharField(blank=True, max_length=150, null=True)),
                ('ClassId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ClassMaster.class')),
                ('ExamType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MarksheetMaster.examtype')),
                ('SubjectId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SubjectMaster.subject')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
    ]
