# Generated by Django 4.1.3 on 2024-05-08 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolMaster', '0003_academicyear'),
        ('MarksheetMaster', '0002_exams'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='AcademicYearId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolMaster.academicyear'),
        ),
    ]
