# Generated by Django 4.1.3 on 2024-05-09 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarksheetMaster', '0003_exams_academicyearid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtype',
            name='Marks',
        ),
        migrations.CreateModel(
            name='ExamTypeMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('Marks', models.CharField(blank=True, max_length=150, null=True)),
                ('school_code', models.CharField(blank=True, max_length=150, null=True)),
                ('Typeid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MarksheetMaster.examtype')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
    ]
