# Generated by Django 4.2.13 on 2024-05-28 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Parent_StudentMaster', '0003_alter_students_photo'),
        ('SchoolMaster', '0008_delete_announcement'),
        ('ClassMaster', '0001_initial'),
        ('MarksheetMaster', '0004_remove_examtype_marks_examtypemarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=150, null=True)),
                ('RollNo', models.CharField(blank=True, max_length=150, null=True)),
                ('ObtainedMarks', models.CharField(blank=True, max_length=255, null=True)),
                ('SchoolCode', models.CharField(blank=True, max_length=150, null=True)),
                ('AcademicYearId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolMaster.academicyear')),
                ('ClassId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ClassMaster.class')),
                ('Exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MarksheetMaster.exams')),
                ('Student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Parent_StudentMaster.students')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
    ]
