# Generated by Django 5.0.6 on 2024-05-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarksheetMaster', '0005_marksheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=550, null=True)),
                ('school_code', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
    ]
