# Generated by Django 5.0.6 on 2024-05-29 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarksheetMaster', '0006_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MarksheetMaster.exam'),
        ),
    ]
