# Generated by Django 5.0.6 on 2024-05-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarksheetMaster', '0007_exams_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='subID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
