# Generated by Django 4.2.13 on 2024-05-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarksheetMaster', '0007_exams_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='SubID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
