# Generated by Django 4.2.13 on 2024-05-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarksheetMaster', '0008_marksheet_subid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='AcademicYearId',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='ClassId',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='Exam',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='Student',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
