# Generated by Django 4.2.13 on 2024-06-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarksheetMaster', '0009_alter_marksheet_academicyearid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='OutOfMarks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
