# Generated by Django 5.0.6 on 2024-06-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarksheetMaster', '0010_marksheet_outofmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='passingMarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
