# Generated by Django 5.0.6 on 2024-06-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarksheetMaster', '0011_exams_passingmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtypemarks',
            name='passingmarks',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
