# Generated by Django 5.0.6 on 2024-06-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarksheetMaster', '0012_examtypemarks_passingmarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exams',
            old_name='passingMarks',
            new_name='passingmarks',
        ),
    ]
