# Generated by Django 4.1.3 on 2024-05-18 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessageMaster', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Messages',
        ),
    ]
