# Generated by Django 4.1.3 on 2024-05-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageMaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('from_user_id', models.CharField(blank=True, max_length=150, null=True)),
                ('from_user_str', models.CharField(max_length=500, null=True)),
                ('message', models.TextField()),
                ('short_message', models.TextField()),
                ('to_user_id', models.CharField(max_length=150)),
                ('to_user_str', models.CharField(max_length=500)),
                ('IsRead', models.BooleanField(default=False)),
                ('date_str', models.CharField(max_length=500, null=True)),
                ('school_code', models.CharField(blank=True, max_length=150, null=True)),
                ('StudentCode', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
