# Generated by Django 4.1.3 on 2024-05-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageMaster', '0002_rename_message_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='from_user_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='to_user_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
