# Generated by Django 5.0.6 on 2024-07-10 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessageMaster', '0003_messages_from_user_studentcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='from_user_studentcode',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='to_user_studentcode',
        ),
    ]
