# Generated by Django 4.1.3 on 2024-05-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageMaster', '0003_alter_messages_from_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='StudentCode',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='to_user_id',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='messages',
            name='to_user_str',
            field=models.CharField(max_length=500),
        ),
    ]
