# Generated by Django 5.0.6 on 2024-07-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageMaster', '0004_remove_messages_from_user_studentcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='StudentCode',
            new_name='from_user_studentcode',
        ),
        migrations.AddField(
            model_name='messages',
            name='to_user_studentcode',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
