# Generated by Django 4.1.3 on 2024-05-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageMaster', '0004_alter_messages_studentcode_alter_messages_to_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='short_message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
