# Generated by Django 5.0.6 on 2024-07-10 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessageMaster', '0005_rename_studentcode_messages_from_user_studentcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='IsRead',
        ),
    ]
