# Generated by Django 5.0.6 on 2024-07-10 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageMaster', '0006_remove_messages_isread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_str',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
