# Generated by Django 5.0.6 on 2024-07-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageMaster', '0007_alter_messages_date_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_str',
            field=models.DateField(blank=True, null=True),
        ),
    ]
