# Generated by Django 4.1.3 on 2024-04-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesignationMaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='school_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='designationName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
