# Generated by Django 4.1.3 on 2024-04-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent_StudentMaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='ParentId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
