# Generated by Django 4.1.3 on 2024-05-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent_StudentMaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclasslog',
            name='RollNo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
