# Generated by Django 5.0.6 on 2024-05-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent_StudentMaster', '0002_studentclasslog_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
