# Generated by Django 4.1.3 on 2024-04-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent_StudentMaster', '0003_alter_students_studentclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='ParentId',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
