# Generated by Django 4.2.13 on 2024-06-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent_StudentMaster', '0003_alter_students_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclasslog',
            name='promote_class',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
