# Generated by Django 4.1.3 on 2024-04-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent_StudentMaster', '0004_alter_students_parentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='BloodGroup',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
