# Generated by Django 4.2.13 on 2024-06-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent_StudentMaster', '0004_studentclasslog_promote_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclasslog',
            name='exam',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
