# Generated by Django 4.2.13 on 2024-06-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent_StudentMaster', '0005_studentclasslog_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclasslog',
            name='exam',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
