# Generated by Django 4.1.3 on 2024-04-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent_StudentMaster', '0006_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='BloodGroup',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
