# Generated by Django 5.0.6 on 2024-06-06 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Parent_StudentMaster', '0007_rename_exam_studentclasslog_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclasslog',
            name='Exam',
        ),
    ]
