# Generated by Django 4.1.3 on 2024-05-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent_StudentMaster', '0008_studentclasslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='StudentImages/', verbose_name='Student Photo'),
        ),
    ]
