# Generated by Django 4.1.3 on 2024-05-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent_StudentMaster', '0009_students_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclasslog',
            name='RollNo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='RollNo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
