# Generated by Django 4.1.3 on 2024-05-17 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolMaster', '0004_school_school_logo'),
        ('Parent_StudentMaster', '0010_studentclasslog_rollno_students_rollno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('Date', models.DateField(null=True)),
                ('classid', models.JSONField(null=True)),
                ('Announcementtext', models.TextField(blank=True, null=True)),
                ('school_code', models.CharField(blank=True, max_length=150, null=True)),
                ('AcademicyearId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolMaster.academicyear')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
    ]
