# Generated by Django 4.1.3 on 2024-05-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent_StudentMaster', '0010_primary_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Primary_Student',
        ),
        migrations.AddField(
            model_name='students',
            name='primary_student',
            field=models.BooleanField(default=False),
        ),
    ]
